### ISSUE TITLE
Feedback for “Other Frameworks”

### ISSUE THREAD

**Issue by amrishshah** [The-Commit-Company/frappe-react-sdk#34]
is this module can be used in next js framework ?

**Comment by nikkothari22** [comment]
Hey @amrishshah - technically, yes. Under the hood, frappe-react-sdk uses SWR (made by the Vercel team themselves). However, all API calls will be made from the client - not from the server. You can read more about SWR's support for React Server components and NextJS here: https://swr.vercel.app/docs/with-nextjs. This is okay if you wish to make API calls from the client though.

If you want to make full use of NextJS's SSR capabilities, you would have to make those API calls from server components in NextJS. While you can't use frappe-react-sdk for that, you can use frappe-js-sdk (the library being used under the hood in frappe-react-sdk) to interface with your Frappe server.

**Comment by nikkothari22** [comment]
I haven't used NextJS in a while (and haven't ever tried out RSCs), so won't help be of much help to you. 

But in short:
1. On the client - you can use frappe-react-sdk. We use this on our client side React apps with Vite. 
2. On the server - you can use frappe-js-sdk - but I'm not sure how NextJS handles cookies so that might be an issue.

**Comment by amrishshah** [comment]
Thanks for the tip!
